In [1]:
import numpy as np

In [12]:
"""
For sample: variance = (x1 - mu)^2 + (x2 -mu)^2 + ... + (xm - mu)^2 / (m-1)
For population: variance = (x1 - mu)^2 + (x2 -mu)^2 + ... + (xm - mu)^2 / (m)

Why population has m term as dinominator and sample has (m-1)?
  Answer: If we random sample from the resonably large population and compute the variance of the sample, and
  then we want to infere the variance for the population by calculating the variance for sample.
  
  Sample variance is always less than the population variance, and in infering variance for population is a bit less than the real 
  population variance. However, how many random sample we take and compute we will get the same results.
  
  To avoid that bias we need to divide it by (m-1) to get the close approximate of the population variance.

"""

# data
'''
   x  | y
--------
  3  | 7
  2  | 4 
'''

A = np.array([[3,7],[2,4]])

In [14]:
np.cov(A.T) # using python's covariance 

array([[0.5, 1.5],
       [1.5, 4.5]])

In [3]:
A = A - np.mean(A, axis=0)

In [4]:
A

array([[ 0.5,  1.5],
       [-0.5, -1.5]])

In [6]:
covariance_matrix = np.dot(A.T, A)

In [7]:
covariance_matrix

array([[0.5, 1.5],
       [1.5, 4.5]])