In [47]:
# Load the boston housing prices dataset
# do regresssion using gradient descent algorithm
import numpy as np
from sklearn import datasets, model_selection, preprocessing, linear_model
import matplotlib.pyplot as plt

In [2]:
# Hypothesis: LINEAR : h(x) = theta0*x0 + theta*x1 + ...., where x0=

In [21]:
# Load the dataset
boston = datasets.load_boston()
x = boston.data
y = boston.target

In [22]:
### Data preprocessing

## feature scaling/ mean normalization
x = preprocessing.scale(x)

## splitting dataset into train,test 
x_train, x_test, y_train ,y_test = model_selection.train_test_split(x,y, test_size=0.3, random_state=42)
m, n = x_train.shape[0], len(boston.feature_names)
# constructing A, b arrays
ones = np.ones((m,1))
A = np.append(ones, x_train, axis=1)
b = y_train

In [45]:
def learn_params(theta, A, b, m,n, alpha=0.01):
    for i in range(0,n+1):
        value = 0
        for j in range(0,m):
            value += (np.dot(theta.T, np.reshape(A[j:j+1,], (n+1,1)))[0,0]-b[j])*A[j,i]
        theta[i,0] -= alpha*value
    return theta
            

In [46]:
# Initialize theta vector to all zeros
theta = np.zeros((n+1,1)) # theta = [theta0, theta1, ...thetan]
# define learning rate 
alpha = 0.01
copy_theta = np.copy(theta)

while True:
    new_theta = learn_params(np.copy(theta), A, b, m,n, alpha)
    # convergence condition is sum of squrred errors should be minimum
    J = sum((np.dot(A, theta) - np.reshape(b, (m,1)))**2)[0]
    e = sum((np.dot(A, new_theta) - np.reshape(b,(m,1)))**2)[0]
    #print(J, e)
    #print(new_theta)
    
    if abs(J-e)<=0.001:
        print(new_theta)
        break
    theta = np.copy(new_theta)
        

s [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[ 81.476     ]
 [ -8.41261427]
 [  4.55471562]
 [  4.83432699]
 [  2.20689568]
 [-12.50921884]
 [ -7.25687557]
 [ 20.10649494]
 [ 26.77997986]
 [ 38.57635388]
 [-88.12432983]
 [ 93.69264524]
 [-32.3632436 ]
 [-56.31560015]]
s [[ 81.476     ]
 [ -8.41261427]
 [  4.55471562]
 [  4.83432699]
 [  2.20689568]
 [-12.50921884]
 [ -7.25687557]
 [ 20.10649494]
 [ 26.77997986]
 [ 38.57635388]
 [-88.12432983]
 [ 93.69264524]
 [-32.3632436 ]
 [-56.31560015]]
[[ -98.83244983]
 [  58.91648305]
 [  30.61633723]
 [  86.76730103]
 [  26.0073382 ]
 [ -86.8318634 ]
 [  43.44851288]
 [ 154.91719041]
 [ 211.69200433]
 [ 122.54527466]
 [-202.91706002]
 [-113.25554234]
 [-198.35695941]
 [ 334.30287872]]
s [[ -98.83244983]
 [  58.91648305]
 [  30.61633723]
 [  86.76730103]
 [  26.0073382 ]
 [ -86.8318634 ]
 [  43.44851288]
 [ 154.91719041]
 [ 211.69200433]
 [ 122.54527466]
 [-202.91706002]
 [-113.25554234]
 [-198.35695941]

s [[ 8.25290149e+11]
 [ 5.48137542e+12]
 [ 5.54620116e+12]
 [ 5.36335136e+12]
 [-1.76045320e+12]
 [-9.70465661e+12]
 [-9.37582537e+12]
 [ 1.30419102e+13]
 [ 2.35059427e+13]
 [ 2.02854973e+13]
 [-4.51207533e+13]
 [ 3.46294016e+13]
 [-3.42922432e+13]
 [-2.43557876e+13]]
[[ 1.28939573e+13]
 [ 1.58071265e+13]
 [-2.10799029e+13]
 [ 2.80782681e+12]
 [ 2.68552988e+13]
 [ 1.89772672e+13]
 [ 3.40563593e+13]
 [-3.10007663e+13]
 [-6.01894913e+13]
 [-1.10043477e+14]
 [ 2.68127164e+14]
 [-3.73847392e+14]
 [ 9.69694999e+13]
 [ 3.09183307e+14]]
s [[ 1.28939573e+13]
 [ 1.58071265e+13]
 [-2.10799029e+13]
 [ 2.80782681e+12]
 [ 2.68552988e+13]
 [ 1.89772672e+13]
 [ 3.40563593e+13]
 [-3.10007663e+13]
 [-6.01894913e+13]
 [-1.10043477e+14]
 [ 2.68127164e+14]
 [-3.73847392e+14]
 [ 9.69694999e+13]
 [ 3.09183307e+14]]
[[-1.26566886e+14]
 [-3.33931277e+14]
 [-7.15785036e+13]
 [-2.38226202e+14]
 [-1.23272374e+14]
 [ 2.56247099e+14]
 [ 1.30374002e+14]
 [-3.05487273e+14]
 [-5.16251376e+14]
 [-2.69132955e+13]
 [-1.

[[-6.15897082e+25]
 [-1.98503840e+25]
 [ 1.86173319e+26]
 [ 5.05970476e+25]
 [-1.71535777e+26]
 [-2.25873888e+26]
 [-3.06604724e+26]
 [ 3.34266528e+26]
 [ 6.27541444e+26]
 [ 8.65441650e+26]
 [-2.05533447e+27]
 [ 2.51504034e+27]
 [-9.66964496e+26]
 [-2.02629282e+27]]
s [[-6.15897082e+25]
 [-1.98503840e+25]
 [ 1.86173319e+26]
 [ 5.05970476e+25]
 [-1.71535777e+26]
 [-2.25873888e+26]
 [-3.06604724e+26]
 [ 3.34266528e+26]
 [ 6.27541444e+26]
 [ 8.65441650e+26]
 [-2.05533447e+27]
 [ 2.51504034e+27]
 [-9.66964496e+26]
 [-2.02629282e+27]]
[[ 8.65948884e+26]
 [ 2.05688031e+27]
 [ 1.37313809e+26]
 [ 1.36419980e+27]
 [ 1.02065313e+27]
 [-1.19503318e+27]
 [-3.04158148e+26]
 [ 1.32287943e+27]
 [ 2.13947491e+27]
 [-1.20582665e+27]
 [ 3.92146115e+27]
 [-1.18745119e+28]
 [-2.61333201e+27]
 [ 1.08270744e+28]]
s [[ 8.65948884e+26]
 [ 2.05688031e+27]
 [ 1.37313809e+26]
 [ 1.36419980e+27]
 [ 1.02065313e+27]
 [-1.19503318e+27]
 [-3.04158148e+26]
 [ 1.32287943e+27]
 [ 2.13947491e+27]
 [-1.20582665e+27]
 [ 3.

[[ 2.12949944e+38]
 [-4.79441849e+38]
 [-1.49302980e+39]
 [-8.14842299e+38]
 [ 1.02197716e+39]
 [ 2.12848317e+39]
 [ 2.48289301e+39]
 [-3.01252620e+39]
 [-5.54955236e+39]
 [-6.37198617e+39]
 [ 1.48066975e+40]
 [-1.59369216e+40]
 [ 8.34048829e+39]
 [ 1.24513469e+40]]
s [[ 2.12949944e+38]
 [-4.79441849e+38]
 [-1.49302980e+39]
 [-8.14842299e+38]
 [ 1.02197716e+39]
 [ 2.12848317e+39]
 [ 2.48289301e+39]
 [-3.01252620e+39]
 [-5.54955236e+39]
 [-6.37198617e+39]
 [ 1.48066975e+40]
 [-1.59369216e+40]
 [ 8.34048829e+39]
 [ 1.24513469e+40]]
[[-5.58860045e+39]
 [-1.17059698e+40]
 [ 1.54448143e+39]
 [-6.97289378e+39]
 [-7.81442966e+39]
 [ 3.85605440e+39]
 [-2.10893605e+39]
 [-3.22373016e+39]
 [-4.13517396e+39]
 [ 1.74540996e+40]
 [-4.73448697e+40]
 [ 9.73574789e+40]
 [ 2.56457151e+39]
 [-8.54588320e+40]]
s [[-5.58860045e+39]
 [-1.17059698e+40]
 [ 1.54448143e+39]
 [-6.97289378e+39]
 [-7.81442966e+39]
 [ 3.85605440e+39]
 [-2.10893605e+39]
 [-3.22373016e+39]
 [-4.13517396e+39]
 [ 1.74540996e+40]
 [-4.

 [ 6.30588098e+53]]
s [[ 3.37780967e+52]
 [ 5.92712325e+52]
 [-2.71262896e+52]
 [ 2.87405929e+52]
 [ 5.62152637e+52]
 [ 4.92059768e+51]
 [ 4.25505584e+52]
 [-1.94102752e+52]
 [-4.58045794e+52]
 [-1.76289829e+53]
 [ 4.47458036e+53]
 [-7.40119668e+53]
 [ 8.91771946e+52]
 [ 6.30588098e+53]]
[[-2.45878246e+53]
 [-7.22502406e+53]
 [-2.53571205e+53]
 [-5.49024143e+53]
 [-1.81448128e+53]
 [ 6.79768962e+53]
 [ 4.45828942e+53]
 [-8.44737511e+53]
 [-1.46138964e+54]
 [-5.11492181e+53]
 [ 8.32010205e+53]
 [ 1.54221444e+54]
 [ 2.00456095e+54]
 [-1.69849048e+54]]
s [[-2.45878246e+53]
 [-7.22502406e+53]
 [-2.53571205e+53]
 [-5.49024143e+53]
 [-1.81448128e+53]
 [ 6.79768962e+53]
 [ 4.45828942e+53]
 [-8.44737511e+53]
 [-1.46138964e+54]
 [-5.11492181e+53]
 [ 8.32010205e+53]
 [ 1.54221444e+54]
 [ 2.00456095e+54]
 [-1.69849048e+54]]
[[ 4.11998018e+53]
 [ 2.81954815e+54]
 [ 2.91812317e+54]
 [ 2.79840970e+54]
 [-9.54964732e+53]
 [-5.09470927e+54]
 [-4.92370191e+54]
 [ 6.86610386e+54]
 [ 1.23702240e+55]
 [ 1

[[-1.87403179e+65]
 [-2.39111509e+65]
 [ 2.89546828e+65]
 [-5.46928588e+64]
 [-3.82100994e+65]
 [-2.47908867e+65]
 [-4.69006937e+65]
 [ 4.11673455e+65]
 [ 8.07451098e+65]
 [ 1.53137166e+66]
 [-3.74317773e+66]
 [ 5.29169966e+66]
 [-1.31287343e+66]
 [-4.39003074e+66]]
s [[-1.87403179e+65]
 [-2.39111509e+65]
 [ 2.89546828e+65]
 [-5.46928588e+64]
 [-3.82100994e+65]
 [-2.47908867e+65]
 [-4.69006937e+65]
 [ 4.11673455e+65]
 [ 8.07451098e+65]
 [ 1.53137166e+66]
 [-3.74317773e+66]
 [ 5.29169966e+66]
 [-1.31287343e+66]
 [-4.39003074e+66]]
[[ 1.78891387e+66]
 [ 4.76063218e+66]
 [ 1.07624301e+66]
 [ 3.41537399e+66]
 [ 1.70828468e+66]
 [-3.72623352e+66]
 [-1.95604928e+66]
 [ 4.46559421e+66]
 [ 7.57379194e+66]
 [ 6.62823060e+65]
 [ 9.15335946e+65]
 [-1.77736533e+67]
 [-1.00619781e+67]
 [ 1.72855701e+67]]
s [[ 1.78891387e+66]
 [ 4.76063218e+66]
 [ 1.07624301e+66]
 [ 3.41537399e+66]
 [ 1.70828468e+66]
 [-3.72623352e+66]
 [-1.95604928e+66]
 [ 4.46559421e+66]
 [ 7.57379194e+66]
 [ 6.62823060e+65]
 [ 9.

[[ 5.19743002e+79]
 [ 1.96512684e+80]
 [ 1.21456939e+80]
 [ 1.67178455e+80]
 [ 4.08959685e+78]
 [-2.51349750e+80]
 [-2.07913408e+80]
 [ 3.26908652e+80]
 [ 5.78937631e+80]
 [ 3.78136161e+80]
 [-7.91077610e+80]
 [ 2.52518003e+80]
 [-8.22972723e+80]
 [-7.60197211e+79]]
s [[ 5.19743002e+79]
 [ 1.96512684e+80]
 [ 1.21456939e+80]
 [ 1.67178455e+80]
 [ 4.08959685e+78]
 [-2.51349750e+80]
 [-2.07913408e+80]
 [ 3.26908652e+80]
 [ 5.78937631e+80]
 [ 3.78136161e+80]
 [-7.91077610e+80]
 [ 2.52518003e+80]
 [-8.22972723e+80]
 [-7.60197211e+79]]
[[ 1.20198817e+80]
 [-2.28953440e+80]
 [-7.78168216e+80]
 [-4.11288647e+80]
 [ 5.44247034e+80]
 [ 1.09897489e+81]
 [ 1.29329734e+81]
 [-1.55925469e+81]
 [-2.87548885e+81]
 [-3.33971812e+81]
 [ 7.77220430e+81]
 [-8.44506711e+81]
 [ 4.32786824e+81]
 [ 6.61415673e+81]]
s [[ 1.20198817e+80]
 [-2.28953440e+80]
 [-7.78168216e+80]
 [-4.11288647e+80]
 [ 5.44247034e+80]
 [ 1.09897489e+81]
 [ 1.29329734e+81]
 [-1.55925469e+81]
 [-2.87548885e+81]
 [-3.33971812e+81]
 [ 7.

[[-4.42049653e+92]
 [-1.46067920e+93]
 [-7.06512866e+92]
 [-1.17588911e+93]
 [-1.99653363e+92]
 [ 1.61976006e+93]
 [ 1.22138813e+93]
 [-2.06662900e+93]
 [-3.62470266e+93]
 [-1.91690245e+93]
 [ 3.76812364e+93]
 [ 6.35870802e+92]
 [ 5.07851411e+93]
 [-1.44672514e+93]]
s [[-4.42049653e+92]
 [-1.46067920e+93]
 [-7.06512866e+92]
 [-1.17588911e+93]
 [-1.99653363e+92]
 [ 1.61976006e+93]
 [ 1.22138813e+93]
 [-2.06662900e+93]
 [-3.62470266e+93]
 [-1.91690245e+93]
 [ 3.76812364e+93]
 [ 6.35870802e+92]
 [ 5.07851411e+93]
 [-1.44672514e+93]]
[[-2.49254612e+91]
 [ 3.71337499e+93]
 [ 5.84219603e+93]
 [ 4.36534280e+93]
 [-2.98149344e+93]
 [-9.24089012e+93]
 [-9.78470419e+93]
 [ 1.27426234e+94]
 [ 2.32023810e+94]
 [ 2.32978108e+94]
 [-5.31156520e+94]
 [ 5.01835062e+94]
 [-3.43214941e+94]
 [-3.77932481e+94]]
s [[-2.49254612e+91]
 [ 3.71337499e+93]
 [ 5.84219603e+93]
 [ 4.36534280e+93]
 [-2.98149344e+93]
 [-9.24089012e+93]
 [-9.78470419e+93]
 [ 1.27426234e+94]
 [ 2.32023810e+94]
 [ 2.32978108e+94]
 [-5.

[[-4.85185008e+104]
 [-8.68170551e+104]
 [ 3.63597672e+104]
 [-4.32447032e+104]
 [-7.94319997e+104]
 [-2.93624681e+103]
 [-5.67567068e+104]
 [ 2.21875910e+104]
 [ 5.54303544e+104]
 [ 2.42858370e+105]
 [-6.19114070e+105]
 [ 1.04089823e+106]
 [-1.12771271e+105]
 [-8.89074012e+105]]
s [[-4.85185008e+104]
 [-8.68170551e+104]
 [ 3.63597672e+104]
 [-4.32447032e+104]
 [-7.94319997e+104]
 [-2.93624681e+103]
 [-5.67567068e+104]
 [ 2.21875910e+104]
 [ 5.54303544e+104]
 [ 2.42858370e+105]
 [-6.19114070e+105]
 [ 1.04089823e+106]
 [-1.12771271e+105]
 [-8.89074012e+105]]
[[ 3.45221763e+105]
 [ 1.02370846e+106]
 [ 3.70418357e+105]
 [ 7.81695134e+105]
 [ 2.47490383e+105]
 [-9.77258924e+105]
 [-6.50074783e+105]
 [ 1.21751225e+106]
 [ 2.10912739e+106]
 [ 7.75435603e+105]
 [-1.29868447e+106]
 [-2.04259471e+106]
 [-2.89917214e+106]
 [ 2.29244703e+106]]
s [[ 3.45221763e+105]
 [ 1.02370846e+106]
 [ 3.70418357e+105]
 [ 7.81695134e+105]
 [ 2.47490383e+105]
 [-9.77258924e+105]
 [-6.50074783e+105]
 [ 1.21751225

 [ 6.22108973e+118]]
s [[ 2.71636445e+117]
 [ 3.60894579e+117]
 [-3.97518732e+117]
 [ 9.59812184e+116]
 [ 5.42649898e+117]
 [ 3.24159913e+117]
 [ 6.42671048e+117]
 [-5.48237914e+117]
 [-1.08214865e+118]
 [-2.13145753e+118]
 [ 5.22462503e+118]
 [-7.48115956e+118]
 [ 1.77252345e+118]
 [ 6.22108973e+118]]
[[-2.52525553e+118]
 [-6.78048756e+118]
 [-1.61270371e+118]
 [-4.89160698e+118]
 [-2.36424187e+118]
 [ 5.40828964e+118]
 [ 2.91775728e+118]
 [-6.50802355e+118]
 [-1.10631976e+119]
 [-1.30756470e+118]
 [-4.44728852e+117]
 [ 2.42926994e+119]
 [ 1.47535383e+119]
 [-2.38013194e+119]]
s [[-2.52525553e+118]
 [-6.78048756e+118]
 [-1.61270371e+118]
 [-4.89160698e+118]
 [-2.36424187e+118]
 [ 5.40828964e+118]
 [ 2.91775728e+118]
 [-6.50802355e+118]
 [-1.10631976e+119]
 [-1.30756470e+118]
 [-4.44728852e+117]
 [ 2.42926994e+119]
 [ 1.47535383e+119]
 [-2.38013194e+119]]
[[ 7.26038335e+118]
 [ 3.43212939e+119]
 [ 2.76127089e+119]
 [ 3.13745056e+119]
 [-4.80468716e+118]
 [-5.20023285e+119]
 [-4.6878246

[[-1.33812829e+130]
 [-7.21794585e+129]
 [ 3.59472213e+130]
 [ 7.60134848e+129]
 [-3.49955472e+130]
 [-4.19324151e+130]
 [-5.90733097e+130]
 [ 6.27833715e+130]
 [ 1.18429883e+131]
 [ 1.70118250e+131]
 [-4.05741467e+131]
 [ 5.08053700e+131]
 [-1.83602163e+131]
 [-4.11381588e+131]]
s [[-1.33812829e+130]
 [-7.21794585e+129]
 [ 3.59472213e+130]
 [ 7.60134848e+129]
 [-3.49955472e+130]
 [-4.19324151e+130]
 [-5.90733097e+130]
 [ 6.27833715e+130]
 [ 1.18429883e+131]
 [ 1.70118250e+131]
 [-4.05741467e+131]
 [ 5.08053700e+131]
 [-1.83602163e+131]
 [-4.11381588e+131]]
[[ 1.74389512e+131]
 [ 4.22538776e+131]
 [ 4.05373846e+130]
 [ 2.84438362e+131]
 [ 1.99038554e+131]
 [-2.61105517e+131]
 [-8.28356741e+130]
 [ 2.94578910e+131]
 [ 4.82133799e+131]
 [-1.91561871e+131]
 [ 6.72903235e+131]
 [-2.28150027e+132]
 [-6.02095548e+131]
 [ 2.09780918e+132]]
s [[ 1.74389512e+131]
 [ 4.22538776e+131]
 [ 4.05373846e+130]
 [ 2.84438362e+131]
 [ 1.99038554e+131]
 [-2.61105517e+131]
 [-8.28356741e+130]
 [ 2.94578910

[[ 1.92295045e+142]
 [ 7.39809214e+142]
 [ 4.69124912e+142]
 [ 6.33414103e+142]
 [ 5.15394283e+140]
 [-9.61292569e+142]
 [-8.02337528e+142]
 [ 1.25269285e+143]
 [ 2.22058083e+143]
 [ 1.47765060e+143]
 [-3.10596199e+143]
 [ 1.10271072e+143]
 [-3.16108793e+143]
 [-4.07929094e+142]]
s [[ 1.92295045e+142]
 [ 7.39809214e+142]
 [ 4.69124912e+142]
 [ 6.33414103e+142]
 [ 5.15394283e+140]
 [-9.61292569e+142]
 [-8.02337528e+142]
 [ 1.25269285e+143]
 [ 2.22058083e+143]
 [ 1.47765060e+143]
 [-3.10596199e+143]
 [ 1.10271072e+143]
 [-3.16108793e+143]
 [-4.07929094e+142]]
[[ 5.05067347e+142]
 [-7.40213213e+142]
 [-2.92604763e+143]
 [-1.46920912e+143]
 [ 2.11330036e+143]
 [ 4.07241679e+143]
 [ 4.85847739e+143]
 [-5.80035766e+143]
 [-1.07146525e+144]
 [-1.26653633e+144]
 [ 2.95416317e+144]
 [-3.25548318e+144]
 [ 1.61628294e+144]
 [ 2.55882637e+144]]
s [[ 5.05067347e+142]
 [-7.40213213e+142]
 [-2.92604763e+143]
 [-1.46920912e+143]
 [ 2.11330036e+143]
 [ 4.07241679e+143]
 [ 4.85847739e+143]
 [-5.80035766

/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in add
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:10: RuntimeWarning: overflow encountered in add
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in square
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in double_scalars
  from ipykernel import kernelapp as app


[[-5.15148293e+152]
 [-1.98780478e+153]
 [-1.26589588e+153]
 [-1.70376548e+153]
 [-9.19428121e+150]
 [ 2.58974534e+153]
 [ 2.16472283e+153]
 [-3.37586876e+153]
 [-5.98517039e+153]
 [-3.99489810e+153]
 [ 8.40352856e+153]
 [-3.03198462e+153]
 [ 8.52213495e+153]
 [ 1.15138784e+153]]
s [[-5.15148293e+152]
 [-1.98780478e+153]
 [-1.26589588e+153]
 [-1.70376548e+153]
 [-9.19428121e+150]
 [ 2.58974534e+153]
 [ 2.16472283e+153]
 [-3.37586876e+153]
 [-5.98517039e+153]
 [-3.99489810e+153]
 [ 8.40352856e+153]
 [-3.03198462e+153]
 [ 8.52213495e+153]
 [ 1.15138784e+153]]
[[-1.38095428e+153]
 [ 1.93357938e+153]
 [ 7.86044579e+153]
 [ 3.91166882e+153]
 [-5.70751272e+153]
 [-1.09127575e+154]
 [-1.30495988e+154]
 [ 1.55533758e+154]
 [ 2.87390776e+154]
 [ 3.40727284e+154]
 [-7.95038663e+154]
 [ 8.78182244e+154]
 [-4.33689709e+154]
 [-6.90661296e+154]]
s [[-1.38095428e+153]
 [ 1.93357938e+153]
 [ 7.86044579e+153]
 [ 3.91166882e+153]
 [-5.70751272e+153]
 [-1.09127575e+154]
 [-1.30495988e+154]
 [ 1.55533758

/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:10: RuntimeWarning: overflow encountered in square
  # Remove the CWD from sys.path while we load stuff.


[[ 3.06765557e+154]
 [ 6.60580120e+154]
 [-5.68475463e+153]
 [ 4.03795058e+154]
 [ 4.14839949e+154]
 [-2.55978245e+154]
 [ 6.89721986e+153]
 [ 2.38016900e+154]
 [ 3.38132945e+154]
 [-8.46934510e+154]
 [ 2.34559105e+155]
 [-5.10595089e+155]
 [-3.05109299e+154]
 [ 4.51187135e+155]]
s [[ 3.06765557e+154]
 [ 6.60580120e+154]
 [-5.68475463e+153]
 [ 4.03795058e+154]
 [ 4.14839949e+154]
 [-2.55978245e+154]
 [ 6.89721986e+153]
 [ 2.38016900e+154]
 [ 3.38132945e+154]
 [-8.46934510e+154]
 [ 2.34559105e+155]
 [-5.10595089e+155]
 [-3.05109299e+154]
 [ 4.51187135e+155]]
[[-1.65410657e+155]
 [-5.53653030e+155]
 [-2.75343465e+155]
 [-4.48273688e+155]
 [-6.91671963e+154]
 [ 6.23508153e+155]
 [ 4.75413880e+155]
 [-7.97301825e+155]
 [-1.39999491e+156]
 [-7.60951152e+155]
 [ 1.50948159e+156]
 [ 1.44383407e+155]
 [ 1.96489319e+156]
 [-4.70997180e+155]]
s [[-1.65410657e+155]
 [-5.53653030e+155]
 [-2.75343465e+155]
 [-4.48273688e+155]
 [-6.91671963e+154]
 [ 6.23508153e+155]
 [ 4.75413880e+155]
 [-7.97301825

[[ 1.30334732e+165]
 [-3.54319016e+166]
 [-5.94975008e+166]
 [-4.29290911e+166]
 [ 3.16848613e+166]
 [ 9.29258209e+166]
 [ 9.95585568e+166]
 [-1.28532652e+167]
 [-2.34364587e+167]
 [-2.39390826e+167]
 [ 5.47196492e+167]
 [-5.26884112e+167]
 [ 3.47345355e+167]
 [ 3.99079230e+167]]
s [[ 1.30334732e+165]
 [-3.54319016e+166]
 [-5.94975008e+166]
 [-4.29290911e+166]
 [ 3.16848613e+166]
 [ 9.29258209e+166]
 [ 9.95585568e+166]
 [-1.28532652e+167]
 [-2.34364587e+167]
 [-2.39390826e+167]
 [ 5.47196492e+167]
 [-5.26884112e+167]
 [ 3.47345355e+167]
 [ 3.99079230e+167]]
[[-1.88042826e+167]
 [-3.44050104e+167]
 [ 1.29182580e+167]
 [-1.76445897e+167]
 [-3.01927401e+167]
 [ 7.24107062e+165]
 [-2.00310244e+167]
 [ 6.03337682e+166]
 [ 1.68126331e+167]
 [ 8.94541556e+167]
 [-2.29308788e+168]
 [ 3.93414005e+168]
 [-3.68012027e+167]
 [-3.37053011e+168]]
s [[-1.88042826e+167]
 [-3.44050104e+167]
 [ 1.29182580e+167]
 [-1.76445897e+167]
 [-3.01927401e+167]
 [ 7.24107062e+165]
 [-2.00310244e+167]
 [ 6.03337682

[[-3.49980846e+178]
 [-1.05127571e+179]
 [-3.96374958e+178]
 [-8.08180208e+178]
 [-2.40373525e+178]
 [ 1.02381113e+179]
 [ 6.93964613e+178]
 [-1.27987847e+179]
 [-2.22117339e+179]
 [-8.69092814e+178]
 [ 1.50562092e+179]
 [ 1.89299363e+179]
 [ 3.06181410e+179]
 [-2.19037238e+179]]
s [[-3.49980846e+178]
 [-1.05127571e+179]
 [-3.96374958e+178]
 [-8.08180208e+178]
 [-2.40373525e+178]
 [ 1.02381113e+179]
 [ 6.93964613e+178]
 [-1.27987847e+179]
 [-2.22117339e+179]
 [-8.69092814e+178]
 [ 1.50562092e+179]
 [ 1.89299363e+179]
 [ 3.06181410e+179]
 [-2.19037238e+179]]
[[ 4.78159854e+178]
 [ 3.82159536e+179]
 [ 4.23789796e+179]
 [ 3.88908166e+179]
 [-1.53812848e+179]
 [-7.26327684e+179]
 [-7.14024997e+179]
 [ 9.82950035e+179]
 [ 1.77438073e+180]
 [ 1.58959885e+180]
 [-3.55691877e+180]
 [ 2.89271930e+180]
 [-2.59312499e+180]
 [-2.07059569e+180]]
s [[ 4.78159854e+178]
 [ 3.82159536e+179]
 [ 4.23789796e+179]
 [ 3.88908166e+179]
 [-1.53812848e+179]
 [-7.26327684e+179]
 [-7.14024997e+179]
 [ 9.82950035

[[-2.87715235e+190]
 [-4.02330856e+190]
 [ 3.89941135e+190]
 [-1.25099723e+190]
 [-5.59062250e+190]
 [-2.93993410e+190]
 [-6.28600746e+190]
 [ 5.12682625e+190]
 [ 1.02241480e+191]
 [ 2.13383929e+191]
 [-5.25185223e+191]
 [ 7.65877647e+191]
 [-1.69441655e+191]
 [-6.38988895e+191]]
s [[-2.87715235e+190]
 [-4.02330856e+190]
 [ 3.89941135e+190]
 [-1.25099723e+190]
 [-5.59062250e+190]
 [-2.93993410e+190]
 [-6.28600746e+190]
 [ 5.12682625e+190]
 [ 1.02241480e+191]
 [ 2.13383929e+191]
 [-5.25185223e+191]
 [ 7.65877647e+191]
 [-1.69441655e+191]
 [-6.38988895e+191]]
[[ 2.57970365e+191]
 [ 7.01357295e+191]
 [ 1.78212180e+191]
 [ 5.09852204e+191]
 [ 2.34722650e+191]
 [-5.73852441e+191]
 [-3.20622689e+191]
 [ 6.94270527e+191]
 [ 1.18375412e+192]
 [ 1.87154312e+191]
 [-7.66418598e+190]
 [-2.36685526e+192]
 [-1.58638556e+192]
 [ 2.34512502e+192]]
s [[ 2.57970365e+191]
 [ 7.01357295e+191]
 [ 1.78212180e+191]
 [ 5.09852204e+191]
 [ 2.34722650e+191]
 [-5.73852441e+191]
 [-3.20622689e+191]
 [ 6.94270527

[[ 1.44663136e+203]
 [ 9.72815652e+202]
 [-3.58790615e+203]
 [-5.97028081e+202]
 [ 3.63268852e+203]
 [ 4.05998691e+203]
 [ 5.88662513e+203]
 [-6.13529217e+203]
 [-1.16162542e+204]
 [-1.72042536e+204]
 [ 4.11596920e+204]
 [-5.23818128e+204]
 [ 1.80938936e+204]
 [ 4.25613970e+204]]
s [[ 1.44663136e+203]
 [ 9.72815652e+202]
 [-3.58790615e+203]
 [-5.97028081e+202]
 [ 3.63268852e+203]
 [ 4.05998691e+203]
 [ 5.88662513e+203]
 [-6.13529217e+203]
 [-1.16162542e+204]
 [-1.72042536e+204]
 [ 4.11596920e+204]
 [-5.23818128e+204]
 [ 1.80938936e+204]
 [ 4.25613970e+204]]
[[-1.79417650e+204]
 [-4.40665185e+204]
 [-5.09163850e+203]
 [-2.99578668e+204]
 [-2.00126543e+204]
 [ 2.83246481e+204]
 [ 1.00652962e+204]
 [-3.23207537e+204]
 [-5.32685798e+204]
 [ 1.60435759e+204]
 [-6.08802782e+204]
 [ 2.26876021e+205]
 [ 6.73645246e+204]
 [-2.09924527e+205]]
s [[-1.79417650e+204]
 [-4.40665185e+204]
 [-5.09163850e+203]
 [-2.99578668e+204]
 [-2.00126543e+204]
 [ 2.83246481e+204]
 [ 1.00652962e+204]
 [-3.23207537

[[-1.90241396e+215]
 [-7.47633411e+215]
 [-4.88483118e+215]
 [-6.45009036e+215]
 [ 7.20630455e+213]
 [ 9.89688154e+215]
 [ 8.34590576e+215]
 [-1.29258787e+216]
 [-2.29383616e+216]
 [-1.55883660e+216]
 [ 3.29372106e+216]
 [-1.29868770e+216]
 [ 3.27070323e+216]
 [ 5.59805885e+215]]
s [[-1.90241396e+215]
 [-7.47633411e+215]
 [-4.88483118e+215]
 [-6.45009036e+215]
 [ 7.20630455e+213]
 [ 9.89688154e+215]
 [ 8.34590576e+215]
 [-1.29258787e+216]
 [-2.29383616e+216]
 [-1.55883660e+216]
 [ 3.29372106e+216]
 [-1.29868770e+216]
 [ 3.27070323e+216]
 [ 5.59805885e+215]]
[[-5.74113669e+215]
 [ 6.00495001e+215]
 [ 2.95273402e+216]
 [ 1.38878948e+216]
 [-2.21368652e+216]
 [-4.03684092e+216]
 [-4.89727211e+216]
 [ 5.77715383e+216]
 [ 1.06938243e+217]
 [ 1.29112663e+217]
 [-3.01955154e+217]
 [ 3.38225020e+217]
 [-1.61758870e+217]
 [-2.66928501e+217]]
s [[-5.74113669e+215]
 [ 6.00495001e+215]
 [ 2.95273402e+216]
 [ 1.38878948e+216]
 [-2.21368652e+216]
 [-4.03684092e+216]
 [-4.89727211e+216]
 [ 5.77715383

[[-3.17904715e+227]
 [-6.96138720e+227]
 [ 4.09795369e+226]
 [-4.31968036e+227]
 [-4.20848268e+227]
 [ 2.93723871e+227]
 [-4.14366368e+226]
 [-2.85862683e+227]
 [-4.21770035e+227]
 [ 8.06331795e+227]
 [-2.26818474e+228]
 [ 5.13847388e+228]
 [ 4.21695396e+227]
 [-4.56073523e+228]]
s [[-3.17904715e+227]
 [-6.96138720e+227]
 [ 4.09795369e+226]
 [-4.31968036e+227]
 [-4.20848268e+227]
 [ 2.93723871e+227]
 [-4.14366368e+226]
 [-2.85862683e+227]
 [-4.21770035e+227]
 [ 8.06331795e+227]
 [-2.26818474e+228]
 [ 5.13847388e+228]
 [ 4.21695396e+227]
 [-4.56073523e+228]]
[[ 1.65939051e+228]
 [ 5.64057176e+228]
 [ 2.89605024e+228]
 [ 4.59787941e+228]
 [ 6.26306760e+227]
 [-6.46731295e+228]
 [-4.99350051e+228]
 [ 8.29104124e+228]
 [ 1.45771894e+229]
 [ 8.16631831e+228]
 [-1.63562832e+229]
 [-3.07556127e+227]
 [-2.04990492e+229]
 [ 3.86705356e+228]]
s [[ 1.65939051e+228]
 [ 5.64057176e+228]
 [ 2.89605024e+228]
 [ 4.59787941e+228]
 [ 6.26306760e+227]
 [-6.46731295e+228]
 [-4.99350051e+228]
 [ 8.29104124

 [-4.20712140e+240]]
[[ 1.96559767e+240]
 [ 3.68550523e+240]
 [-1.21214642e+240]
 [ 1.94849066e+240]
 [ 3.08624346e+240]
 [-2.94936816e+239]
 [ 1.86233326e+240]
 [-3.28558046e+239]
 [-1.20750551e+240]
 [-8.80069015e+240]
 [ 2.27166134e+241]
 [-3.99451300e+241]
 [ 3.03374319e+240]
 [ 3.43459217e+241]]
s [[ 1.96559767e+240]
 [ 3.68550523e+240]
 [-1.21214642e+240]
 [ 1.94849066e+240]
 [ 3.08624346e+240]
 [-2.94936816e+239]
 [ 1.86233326e+240]
 [-3.28558046e+239]
 [-1.20750551e+240]
 [-8.80069015e+240]
 [ 2.27166134e+241]
 [-3.99451300e+241]
 [ 3.03374319e+240]
 [ 3.43459217e+241]]
[[-1.31888259e+241]
 [-4.00617073e+241]
 [-1.56267362e+241]
 [-3.09753442e+241]
 [-8.71012434e+240]
 [ 3.96757856e+241]
 [ 2.73068303e+241]
 [-4.97390119e+241]
 [-8.64477068e+241]
 [-3.54952302e+241]
 [ 6.29903296e+241]
 [ 6.54573545e+241]
 [ 1.19439916e+242]
 [-7.81218221e+241]]
s [[-1.31888259e+241]
 [-4.00617073e+241]
 [-1.56267362e+241]
 [-3.09753442e+241]
 [-8.71012434e+240]
 [ 3.96757856e+241]
 [ 2.7306830

 [ 2.07935174e+252]]
s [[ 3.54432277e+251]
 [ 1.07862545e+252]
 [ 4.23078144e+251]
 [ 8.34779858e+251]
 [ 2.32492415e+251]
 [-1.07120067e+252]
 [-7.39078785e+251]
 [ 1.34351352e+252]
 [ 2.33562434e+252]
 [ 9.66343369e+251]
 [-1.72116159e+252]
 [-1.73239283e+252]
 [-3.22820727e+252]
 [ 2.07935174e+252]]
[[-4.18069576e+251]
 [-3.75303029e+252]
 [-4.34330067e+252]
 [-3.88100780e+252]
 [ 1.66699062e+252]
 [ 7.36269591e+252]
 [ 7.31167677e+252]
 [-9.98896139e+252]
 [-1.80526965e+253]
 [-1.64369988e+253]
 [ 3.68833023e+253]
 [-3.07310451e+253]
 [ 2.64261197e+253]
 [ 2.21941361e+253]]
s [[-4.18069576e+251]
 [-3.75303029e+252]
 [-4.34330067e+252]
 [-3.88100780e+252]
 [ 1.66699062e+252]
 [ 7.36269591e+252]
 [ 7.31167677e+252]
 [-9.98896139e+252]
 [-1.80526965e+253]
 [-1.64369988e+253]
 [ 3.68833023e+253]
 [-3.07310451e+253]
 [ 2.64261197e+253]
 [ 2.21941361e+253]]
[[-1.12503073e+253]
 [-1.63674803e+253]
 [ 1.42628530e+253]
 [-5.63358282e+252]
 [-2.13633317e+253]
 [-9.93348489e+252]
 [-2.2930098

[[ 3.04188879e+263]
 [ 4.45328346e+263]
 [-3.81334990e+263]
 [ 1.55568028e+263]
 [ 5.75452230e+263]
 [ 2.61749481e+263]
 [ 6.12773624e+263]
 [-4.74412426e+263]
 [-9.57861592e+263]
 [-2.13292721e+264]
 [ 5.27211007e+264]
 [-7.83357271e+264]
 [ 1.60943480e+264]
 [ 6.55743212e+264]]
s [[ 3.04188879e+263]
 [ 4.45328346e+263]
 [-3.81334990e+263]
 [ 1.55568028e+263]
 [ 5.75452230e+263]
 [ 2.61749481e+263]
 [ 6.12773624e+263]
 [-4.74412426e+263]
 [-9.57861592e+263]
 [-2.13292721e+264]
 [ 5.27211007e+264]
 [-7.83357271e+264]
 [ 1.60943480e+264]
 [ 6.55743212e+264]]
[[-2.63291531e+264]
 [-7.24782525e+264]
 [-1.95770330e+264]
 [-5.30828057e+264]
 [-2.32554246e+264]
 [ 6.07714254e+264]
 [ 3.50491559e+264]
 [-7.38940102e+264]
 [-1.26341366e+265]
 [-2.46254898e+264]
 [ 2.04082198e+264]
 [ 2.29732326e+265]
 [ 1.70078583e+265]
 [-2.30449489e+265]]
s [[-2.63291531e+264]
 [-7.24782525e+264]
 [-1.95770330e+264]
 [-5.30828057e+264]
 [-2.32554246e+264]
 [ 6.07714254e+264]
 [ 3.50491559e+264]
 [-7.38940102

[[-1.55859238e+276]
 [-1.23564224e+276]
 [ 3.57497567e+276]
 [ 4.24280030e+275]
 [-3.76708729e+276]
 [-3.91312911e+276]
 [-5.85538029e+276]
 [ 5.97479592e+276]
 [ 1.13588268e+277]
 [ 1.73793483e+277]
 [-4.17104319e+277]
 [ 5.39582186e+277]
 [-1.77843857e+277]
 [-4.39921837e+277]]
s [[-1.55859238e+276]
 [-1.23564224e+276]
 [ 3.57497567e+276]
 [ 4.24280030e+275]
 [-3.76708729e+276]
 [-3.91312911e+276]
 [-5.85538029e+276]
 [ 5.97479592e+276]
 [ 1.13588268e+277]
 [ 1.73793483e+277]
 [-4.17104319e+277]
 [ 5.39582186e+277]
 [-1.77843857e+277]
 [-4.39921837e+277]]
[[ 1.84425882e+277]
 [ 4.59050279e+277]
 [ 6.17663679e+276]
 [ 3.15044841e+277]
 [ 2.00951646e+277]
 [-3.06112227e+277]
 [-1.19257534e+277]
 [ 3.52842306e+277]
 [ 5.85075389e+277]
 [-1.27395227e+277]
 [ 5.40313516e+277]
 [-2.25170488e+278]
 [-7.47924540e+277]
 [ 2.09739262e+278]]
s [[ 1.84425882e+277]
 [ 4.59050279e+277]
 [ 6.17663679e+276]
 [ 3.15044841e+277]
 [ 2.00951646e+277]
 [-3.06112227e+277]
 [-1.19257534e+277]
 [ 3.52842306

[[ 6.45915857e+288]
 [-4.52375214e+288]
 [-2.97610786e+289]
 [-1.30186180e+289]
 [ 2.31586883e+289]
 [ 3.99289962e+289]
 [ 4.93028176e+289]
 [-5.74345348e+289]
 [-1.06547444e+290]
 [-1.31495643e+290]
 [ 3.08358085e+290]
 [-3.51034468e+290]
 [ 1.61637090e+290]
 [ 2.78134574e+290]]
s [[ 6.45915857e+288]
 [-4.52375214e+288]
 [-2.97610786e+289]
 [-1.30186180e+289]
 [ 2.31586883e+289]
 [ 3.99289962e+289]
 [ 4.93028176e+289]
 [-5.74345348e+289]
 [-1.06547444e+290]
 [-1.31495643e+290]
 [ 3.08358085e+290]
 [-3.51034468e+290]
 [ 1.61637090e+290]
 [ 2.78134574e+290]]
[[-1.22085961e+290]
 [-2.71084329e+290]
 [ 9.93571018e+288]
 [-1.70261253e+290]
 [-1.58689986e+290]
 [ 1.22004629e+290]
 [-6.19389062e+288]
 [-1.22464489e+290]
 [-1.85061145e+290]
 [ 2.86571571e+290]
 [-8.18457588e+290]
 [ 1.92388096e+291]
 [ 1.96080766e+290]
 [-1.71427648e+291]]
s [[-1.22085961e+290]
 [-2.71084329e+290]
 [ 9.93571018e+288]
 [-1.70261253e+290]
 [-1.58689986e+290]
 [ 1.22004629e+290]
 [-6.19389062e+288]
 [-1.22464489

[[-1.26929652e+301]
 [ 1.18822779e+302]
 [ 2.28840785e+302]
 [ 1.53933511e+302]
 [-1.31534124e+302]
 [-3.48747114e+302]
 [-3.82267229e+302]
 [ 4.85295306e+302]
 [ 8.87290241e+302]
 [ 9.36291135e+302]
 [-2.15046060e+303]
 [ 2.14221086e+303]
 [-1.31995629e+303]
 [-1.63878046e+303]]
s [[-1.26929652e+301]
 [ 1.18822779e+302]
 [ 2.28840785e+302]
 [ 1.53933511e+302]
 [-1.31534124e+302]
 [-3.48747114e+302]
 [-3.82267229e+302]
 [ 4.85295306e+302]
 [ 8.87290241e+302]
 [ 9.36291135e+302]
 [-2.15046060e+303]
 [ 2.14221086e+303]
 [-1.31995629e+303]
 [-1.63878046e+303]]
[[ 7.60318676e+302]
 [ 1.45420504e+303]
 [-4.24548298e+302]
 [ 7.87097339e+302]
 [ 1.17141599e+303]
 [-1.84410878e+302]
 [ 6.46120388e+302]
 [-3.01868813e+301]
 [-2.90690776e+302]
 [-3.22783962e+303]
 [ 8.38521221e+303]
 [-1.50733932e+304]
 [ 9.12694365e+302]
 [ 1.30012615e+304]]
s [[ 7.60318676e+302]
 [ 1.45420504e+303]
 [-4.24548298e+302]
 [ 7.87097339e+302]
 [ 1.17141599e+303]
 [-1.84410878e+302]
 [ 6.46120388e+302]
 [-3.01868813

/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in double_scalars
  
/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars
  


s [[ 1.62520331e+305]
 [ 2.43748579e+305]
 [-1.94716990e+305]
 [ 8.99122730e+304]
 [ 3.02894320e+305]
 [ 1.25534394e+305]
 [ 3.12278078e+305]
 [-2.33745953e+305]
 [-4.75864925e+305]
 [-1.10367373e+306]
 [             inf]
 [             nan]
 [             nan]
 [             nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [

[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]


 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]


s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]


s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
s [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]


KeyboardInterrupt: 

In [48]:
lm = linear_model.LinearRegression()
lm.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [49]:
lm.intercept_

22.50793922138808

In [50]:
lm.coef_

array([-1.14030209,  0.83368112,  0.34230461,  0.792002  , -1.7908376 ,
        2.84189278, -0.30234582, -2.91772744,  2.10815064, -1.46330017,
       -1.97229956,  1.08930453, -3.91000474])