In [2]:
import numpy as np

In [ ]:
# axis defination
# x - pointing vertically downwards, y - pointing horizontally right, z - pointing outof the paper towards you 

In [13]:
#defining a one dimensional numpy array
a = np.array([10])
a.shape

(1,)

In [14]:
np.ndim(a) # Dimension is 1

1

In [18]:
# defining two dimensional array
a = np.array([[1,2,3]]) # One dimension in onther dimension
a.shape

(1, 3)

In [19]:
np.ndim(a) # dimension-2

2

In [25]:
# defining three dimensioal array
a = np.array([[[1,2],[4,5],[7,8]]])
a.shape

(1, 3, 2)

In [38]:
# matrix-vector multiplication
A = np.array([[1,0,2,0],[0,3,0,4],[0,0,5,0],[6,0,0,7]])
v = np.array([2,5,1,8])
np.dot(A,v)

array([ 4, 47,  5, 68])

In [39]:
# matrix-matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[2,0],[1,2]])
np.dot(A,B)

array([[ 4,  4],
       [10,  8]])

In [40]:
# tranpose of a matrix
A.T

array([[1, 3],
       [2, 4]])

In [42]:
# inverse of matrixa
A_inv = np.linalg.inv(A)

In [43]:
np.dot(A, A_inv)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [45]:
# identity matrix
identity = np.identity(n=5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])