In [19]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
X = np.array([[2.7810836,2.550537003],[1.465489372, 2.362125076],[3.396561688, 4.400293529],[1.38807019, 1.850220317],
              [3.06407232, 3.005305973],[7.627531214, 2.759262235],[5.332441248, 2.088626775],[6.922596716, 1.77106367],
              [8.675418651, -0.2420686549],[7.673756466, 3.508563011]])

Y = np.array([0,0,0,0,0,1,1,1,1,1])

In [21]:
# data preprocessing 

In [22]:
# constructing matrices
m,n = X.shape[0], 2
ones = np.ones((m,1))
A = np.append(ones, X, axis=1)
b = Y

In [42]:
def learn_parameters(theta, A, b, m, n, alpha=0.01):
    for i in range(0, n+1):
        value = 0 
        for j in range(0, m):
            exponent = (np.dot(theta.T, np.reshape(A[j:j+1,],(n+1,1))))[0,0]
            value += ((1/(1+np.exp(-exponent))) - b[j])*A[j,i]
        theta[i,0] += alpha*value
    return theta

In [52]:
# initialize parameter vector theta
theta  = np.zeros((n+1, 1))

# define learning rate 
alpha = 0.0001



while True:
    new_theta = learn_parameters(np.copy(theta),A,b,m,n,alpha)
    l = list(b)
    no_of_zeros = l.count(0)
    no_of_ones = l.count(1)
    likelihood_prev, likelihood_new = 1,1
    for i in range(0, m):
        coeff_prev = (np.dot(theta.T, np.reshape(A[i:i+1,], (n+1,1))))[0,0]
        coeff_new = (np.dot(new_theta.T, np.reshape(A[i:i+1,], (n+1,1))))[0,0]
        if b[i] == 0:
            likelihood_prev *= (1-(1/(1+np.exp(-coeff_prev))))
            likelihood_new *= (1-(1/(1+np.exp(-coeff_new))))
        else:
            likelihood_prev *= (1/(1+np.exp(-coeff_prev)))
            likelihood_new *= (1/(1+np.exp(-coeff_new)))
    # convergence condition
    if abs(likelihood_prev-likelihood_new)<=0.00000001:
        print(new_theta)
        break
    theta = np.copy(new_theta)



[[-2.02817388]
 [ 3.4989063 ]
 [-5.13723473]]


In [25]:
from sklearn import linear_model

In [27]:
clf = linear_model.LogisticRegression()
clf.fit(X,Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [28]:
clf.intercept_

array([-0.43104649])

In [29]:
clf.coef_

array([[ 0.80500337, -1.1224275 ]])