In [143]:
import pandas as pd
import numpy as np
from sklearn import linear_model, preprocessing, model_selection

In [144]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00291/airfoil_self_noise.dat', sep='\t' , header=None)
df.head()

0    1       2     3         4        5
0   800  0.0  0.3048  71.3  0.002663  126.201
1  1000  0.0  0.3048  71.3  0.002663  125.201
2  1250  0.0  0.3048  71.3  0.002663  125.951
3  1600  0.0  0.3048  71.3  0.002663  127.591
4  2000  0.0  0.3048  71.3  0.002663  127.461

In [145]:
df = df.dropna()
x = df.values[:, :-1]
y = df.values[:, -1:]

In [146]:
# data preprocessing
# scale the features
x = preprocessing.scale(x)

# split the data into train and test data
x_train, x_test , y_train, y_test = model_selection.train_test_split(x, y, test_size=0.3, random_state=4)

m ,n = x_train.shape[0], x_train.shape[1]
ones = np.ones((m,1))
x_train_ones = np.hstack([ones, x_train], )

In [147]:
# hypothesis; h(x) = theta0 + theta1*x1 + theta2*x2 + ...+ thetan *xn
m, n = x_train_ones.shape[0], x_train_ones.shape[1]

In [148]:
# cost function

def cost_function(theta, x,y,m):
    return sum((np.dot(x, theta) - y)**2)[0]/(2*m)

In [162]:
# gradient descent algorithm

def learn_parameters(theta, x,y, m,n, e=1e-5, alpha=0.01):
    no_of_steps= 0
    while True:
        cost_prev = cost_function(theta, x,y,m)
        # update the parameters
        theta -= (alpha/m)*np.dot(x.T, (np.dot(x,theta)-y))
        cost_curr = cost_function(theta, x,y,m)
        if abs(cost_prev - cost_curr) < e:
            break
        no_of_steps += 1
    return (theta, no_of_steps)

In [164]:
# initialize the thetas
theta = np.zeros((n,1))

# define error tolerance
e = 1000

# define learning rate
alpha = 0.1

learn_parameters(theta, x_train_ones, y_train, e,alpha)

(array([[124.80790396],
        [ -3.86433527],
        [ -2.34779598],
        [ -3.29657998],
        [  1.35529433],
        [ -1.98902067]]), 1442)

In [156]:
# using std sklearn
lgr = linear_model.LinearRegression(normalize=True)
lgr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [157]:
lgr.intercept_

array([124.80796395])

In [158]:
lgr.coef_

array([[-3.88227492, -2.47907063, -3.35221287,  1.36837492, -1.88861772]])