In [17]:
import numpy as np
from sklearn import datasets, preprocessing, model_selection,linear_model
import matplotlib.pyplot as plt

/usr/lib/python3.4/importlib/_bootstrap.py:321: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [9]:
# Load the dataset
boston = datasets.load_boston()
n = len(boston.feature_names) + 1

x = boston.data
m = x.shape[0]
y = np.reshape(boston.target,(m,1))

In [11]:
## Dataset preprocessing

# feature scaling and mean normalization
x = preprocessing.scale(x)

# split the data into train, and test data
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.3, random_state=42)

# constructing matrices
m = x_train.shape[0]

ones = np.ones((m,1))
A_train = np.hstack([ones, x_train])
b_train = y_train

In [13]:
# cost function 
def cost_function(theta, A, b, m):
    return sum((np.dot(A,theta) - b)**2)[0]/(2*m)

In [14]:
# gradient descent algorithm
def gradient_descent(theta, A, b, m,n, e=1e-5, alpha=0.01):
    no_of_steps = 0
    while True:
        cost_prev = cost_function(theta, A, b, m)
        theta -= (alpha/m) * (np.dot((np.dot(A,theta) - b).T, A).T)
        cost_curr = cost_function(theta, A,b,m)
        
        if abs(cost_prev - cost_curr) < e:
            break
        no_of_steps += 1
    return (theta, no_of_steps)

In [15]:
# initialize the parameters ;theta
theta = np.zeros((n,1))

# define error tolerance ; e
e = 1e-10

# define learning rate ; alpha
alpha = 0.01

gradient_descent(theta, A_train, b_train , m,n, e, alpha)

(array([[22.50793368],
        [-1.14021751],
        [ 0.83348584],
        [ 0.34194179],
        [ 0.79206238],
        [-1.7907628 ],
        [ 2.84195399],
        [-0.30239169],
        [-2.91767253],
        [ 2.10713346],
        [-1.46215647],
        [-1.97227773],
        [ 1.08929278],
        [-3.90997268]]), 11948)

In [18]:
# using skearn linear_model
lgr = linear_model.LinearRegression()
lgr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
lgr.intercept_

array([22.50793922])

In [20]:
lgr.coef_

array([[-1.14030209,  0.83368112,  0.34230461,  0.792002  , -1.7908376 ,
         2.84189278, -0.30234582, -2.91772744,  2.10815064, -1.46330017,
        -1.97229956,  1.08930453, -3.91000474]])