In [1]:
import numpy as np
from sklearn import datasets, preprocessing, model_selection,linear_model
import matplotlib.pyplot as plt

In [2]:
# Load the dataset
boston = datasets.load_boston()
n = len(boston.feature_names) + 1

x = boston.data
m = x.shape[0]
y = np.reshape(boston.target,(m,1))

In [3]:
## Dataset preprocessing

# feature scaling and mean normalization
x = preprocessing.scale(x)

# split the data into train, and test data
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.3, random_state=42)

# constructing matrices
m = x_train.shape[0]

ones = np.ones((m,1))
A_train = np.hstack([ones, x_train])
b_train = y_train

In [4]:
# cost function 
def cost_function(theta, A, b, m):
    return sum((np.dot(A,theta) - b)**2)[0]/(2*m)

In [5]:
# newtons optimization algorithm
def newtons_method(theta, A, b, m,n, e=1e-5, alpha=0.01):
    no_of_steps = 0
    while True:
        cost_prev = cost_function(theta, A, b, m)
        grad =  (np.dot((np.dot(A,theta) - b).T, A).T) # gradient vector
        hessian_matrix = np.dot(A.T, A) # hessian matrix
        theta -= (alpha/m) * np.dot(np.linalg.inv(hessian_matrix), grad)
        cost_curr = cost_function(theta, A,b,m)
        
        if abs(cost_prev - cost_curr) < e:
            break
        no_of_steps += 1
    return (theta, no_of_steps)

In [7]:
# initialize the parameters ;theta
theta = np.zeros((n,1))

# define error tolerance ; e
e = 1e-10

# define learning rate ; alpha
alpha = 0.1

newtons_method(theta, A_train, b_train , m,n, e, alpha)

(array([[22.50739037],
        [-1.14027429],
        [ 0.83366079],
        [ 0.34229627],
        [ 0.79198269],
        [-1.79079393],
        [ 2.84182348],
        [-0.30233844],
        [-2.9176563 ],
        [ 2.10809923],
        [-1.46326448],
        [-1.97225147],
        [ 1.08927797],
        [-3.90990939]]), 37594)

In [8]:
# using skearn linear_model
lgr = linear_model.LinearRegression()
lgr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
lgr.intercept_

array([22.50793922])

In [10]:
lgr.coef_

array([[-1.14030209,  0.83368112,  0.34230461,  0.792002  , -1.7908376 ,
         2.84189278, -0.30234582, -2.91772744,  2.10815064, -1.46330017,
        -1.97229956,  1.08930453, -3.91000474]])